# Schema for configuration files of the Paragraphs Sets module.

paragraphs_sets.set.*:
  type: config_entity
  label: 'Paragraphs set'
  mapping:
    id:
      type: string
    description:
      type: text
    label:
      type: label
      label: 'Label'
    icon_uuid:
      type: string
      label: 'Icon uuid'
    paragraphs:
      type: sequence
      mapping:
        type:
          type: string
        data:
          type: sequence
